services:
  uds-fuzz:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile

    image: uds-fuzz
    container_name: uds-fuzz

    stdin_open: true
    tty: true

    command: sleep infinity

    volumes:
      - .:/work
