FROM rust:1.89-bookworm

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY examples ./examples

RUN cargo build --release --example isotp_stateless_ecu

CMD ["cargo", "run", "--release", "--example", "isotp_stateless_ecu"]
